ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
  'Stefan Heimes <stefan_heimes@hotmail.com>': 'Stefan heimes <stefan_heimes@hotmail.com>'
  'Christopher Boelter <c.boelter@cogizz.de>': 'cogizz <c.boelter@cogizz.de>'
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'zonky <info@e-spin.de>'
    - 'zonky2 <info@e-spin.de>'
    - 'Ingolf Steinhardt <git@e-spin.de>'

copy-left:
  'Oliver Hoff <oliver@hofff.com>': Country.php
  'Christian Schiffler <c.schiffler@cyberspectrum.de>':
    - AttributeTypeFactory.php
    - CountryAttributeTypeFactoryTest.php
