ignore:
#  Mini Model <minimodel@metamodel.me>

exclude:
  languages

mapping:
  Andreas Isaak <info@andreas-isaak.de>: Andreas Isaak <andy.jared@googlemail.com>
  Stefan Heimes <stefan_heimes@hotmail.com>: Stefan heimes <stefan_heimes@hotmail.com>
  Christopher Boelter <c.boelter@cogizz.de>: cogizz <c.boelter@cogizz.de>
