services:
    metamodels.attribute_country.factory:
        class: MetaModels\AttributeCountryBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
            - '@event_dispatcher'
        tags:
          - { name: metamodels.attribute_factory }

    MetaModels\AttributeCountryBundle\Migration\AllowNullMigration:
        arguments:
            - '@database_connection'
        tags:
            - name: contao.migration

    MetaModels\AttributeCountryBundle\Schema\DoctrineSchemaGenerator:
        tags:
            - { name: 'metamodels.schema-generator.doctrine' }
